import { Landlord, Listing, TenantProfile } from "@/lib/types";

export const berlinLandlords: Landlord[] = [
    {
        id: "ld-1001",
        name: "UrbanHaus GmbH",
        type: "company",
        email: "kontakt@urbanhaus.example",
        website: "https://urbanhaus.example",
    },
    {
        id: "ld-1002",
        name: "Brix Property",
        type: "company",
        email: "hello@brix-property.example",
        website: "https://brix-property.example",
    },
    {
        id: "ld-1003",
        name: "R. Fischer",
        type: "private",
    },
    {
        id: "ld-2001",
        name: "Berliner Heim eG",
        type: "genossenschaft",
        email: "service@berliner-heim.example",
        website: "https://berliner-heim.example",
    },
    {
        id: "ld-2002",
        name: "NordWohn eG",
        type: "genossenschaft",
        email: "kontakt@nordwohn.example",
        website: "https://nordwohn.example",
    },
];

export const berlinListings: Listing[] = [
    {
        id: "l-1001",
        source: "immobilienscout24",
        sourceListingId: "demo-1001",
        title: "Bright 2-room in Prenzlauer Berg",
        coldRentAmount: 1080,
        warmRentAmount: 1280,
        priceCurrency: "EUR",
        freeFrom: null,
        insertedAt: null,
        isWBSRequired: false,
        floor: 3,
        maxFloor: 5,
        yearOfConstruction: 1910,
        heatingType: null,
        energyType: null,
        energyEfficiencyClass: null,
        energyConsumptionKWhPerYear: null,
        address: "Knaackstrasse 17, 10405 Berlin",
        city: "Berlin",
        country: "DE",
        areaM2: 54,
        rooms: 2,
        listingUrl: null,
        imageUrls: [],
        features: ["cafes", "young", "walkable"],
        isValid: true,
        firstSeenAt: "2025-01-15T10:00:00Z",
        lastSeenAt: "2025-01-15T10:00:00Z",
    },
    {
        id: "l-1002",
        source: "immowelt",
        sourceListingId: "demo-1002",
        title: "Family flat near Tempelhofer Feld",
        coldRentAmount: 1400,
        warmRentAmount: 1650,
        priceCurrency: "EUR",
        freeFrom: null,
        insertedAt: null,
        isWBSRequired: false,
        floor: 1,
        maxFloor: 4,
        yearOfConstruction: 1960,
        heatingType: null,
        energyType: null,
        energyEfficiencyClass: null,
        energyConsumptionKWhPerYear: null,
        address: "Oderstrasse 6, 12051 Berlin",
        city: "Berlin",
        country: "DE",
        areaM2: 79,
        rooms: 3,
        listingUrl: null,
        imageUrls: [],
        features: ["parks", "family", "diverse"],
        isValid: true,
        firstSeenAt: "2025-01-14T10:00:00Z",
        lastSeenAt: "2025-01-14T10:00:00Z",
    },
    {
        id: "l-1003",
        source: "kleinanzeigen",
        sourceListingId: "demo-1003",
        title: "Compact studio in Moabit",
        coldRentAmount: 720,
        warmRentAmount: 890,
        priceCurrency: "EUR",
        freeFrom: null,
        insertedAt: null,
        isWBSRequired: false,
        floor: 2,
        maxFloor: 5,
        yearOfConstruction: 1925,
        heatingType: null,
        energyType: null,
        energyEfficiencyClass: null,
        energyConsumptionKWhPerYear: null,
        address: "Turmstrasse 85, 10551 Berlin",
        city: "Berlin",
        country: "DE",
        areaM2: 31,
        rooms: 1,
        listingUrl: null,
        imageUrls: [],
        features: ["central", "busy", "nightlife"],
        isValid: true,
        firstSeenAt: "2025-01-13T10:00:00Z",
        lastSeenAt: "2025-01-13T10:00:00Z",
    },
    {
        id: "l-2001",
        source: "genossenschaft",
        sourceListingId: "demo-2001",
        title: "Genossenschaft apartment in Lichtenberg",
        coldRentAmount: 780,
        warmRentAmount: 980,
        priceCurrency: "EUR",
        freeFrom: null,
        insertedAt: null,
        isWBSRequired: false,
        floor: 4,
        maxFloor: 6,
        yearOfConstruction: 1975,
        heatingType: null,
        energyType: null,
        energyEfficiencyClass: null,
        energyConsumptionKWhPerYear: null,
        address: "Siegfriedstrasse 112, 10365 Berlin",
        city: "Berlin",
        country: "DE",
        areaM2: 58,
        rooms: 2,
        listingUrl: null,
        imageUrls: [],
        features: ["quiet", "green", "residential"],
        isValid: true,
        firstSeenAt: "2025-01-12T10:00:00Z",
        lastSeenAt: "2025-01-12T10:00:00Z",
    },
    {
        id: "l-2002",
        source: "genossenschaft",
        sourceListingId: "demo-2002",
        title: "Genossenschaft family unit in Pankow",
        coldRentAmount: 1100,
        warmRentAmount: 1320,
        priceCurrency: "EUR",
        freeFrom: null,
        insertedAt: null,
        isWBSRequired: false,
        floor: 2,
        maxFloor: 5,
        yearOfConstruction: 1985,
        heatingType: null,
        energyType: null,
        energyEfficiencyClass: null,
        energyConsumptionKWhPerYear: null,
        address: "Breite Strasse 45, 13187 Berlin",
        city: "Berlin",
        country: "DE",
        areaM2: 84,
        rooms: 3,
        listingUrl: null,
        imageUrls: [],
        features: ["schools", "quiet", "family"],
        isValid: true,
        firstSeenAt: "2025-01-11T10:00:00Z",
        lastSeenAt: "2025-01-11T10:00:00Z",
    },
];

export const districtRentBenchmarkPerM2: Record<string, number> = {
    "Prenzlauer Berg": 22,
    Neukoelln: 19,
    Moabit: 20,
    Lichtenberg: 16,
    Pankow: 18,
};

export const demoTenant: TenantProfile = {
    id: "tn-1001",
    name: "Alex Meyer",
    email: "alex@example.com",
    monthlyNetIncomeEur: 3600,
    householdSize: 2,
    hasPets: false,
    hasSchufa: true,
    stableEmploymentMonths: 28,
    preferredDistricts: ["Pankow", "Prenzlauer Berg", "Lichtenberg"],
};
